/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package epos.slm3d.settingsView;

import epos.slm3d.m3d.BaseFrame;
import epos.slm3d.utils.Events;
import epos.slm3d.m3d.M3DViewer;
import epos.slm3d.settings.UserProfile;
import epos.slm3d.settings.WorkSpace;
import epos.slm3d.utils.StringCrypter;
import epos.slm3d.utils.UNIException;

import java.util.ArrayList;

/**
 *
 * @author romanow
 */
public class Login extends BaseFrame {

    /**
     * Creates new form Login
     */
    private void init(){
        ArrayList<UserProfile> users = WorkSpace.ws().global().userList;
        UserList.removeAll();
        for(UserProfile uu : users){
            UserList.add(uu.name);
            }
        Password.setText("");
        }
    
    public Login() {
        if (!tryToStart()) return;        
        initComponents();
        setBounds(200,200,300,200);
        setTitle("SLM 3D-Принтер");
        try {
            WorkSpace.ws().loadGlobalSettings();
            } catch (UNIException e) {
                MES.setText("Настойки не прочитаны - умолчание");
                WorkSpace.ws().saveSettings();
            }
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserList = new java.awt.Choice();
        jLabel1 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        MES = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(UserList);
        UserList.setBounds(100, 10, 150, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Пароль");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 50, 60, 14);

        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(100, 50, 150, 25);

        jButton1.setText("Войти");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 80, 73, 30);
        getContentPane().add(MES);
        MES.setBounds(40, 120, 220, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    public void onEvent(int code,boolean on, int value, String name) {
        System.out.println(getClass().getSimpleName()+" "+code+" "+on+" "+value+" "+name);
        if (code == Events.LogOut){
            setVisible(true);
            init();
            }
        }
    private void login(){
        ArrayList<UserProfile> users = WorkSpace.ws().global().userList; 
        UserProfile user = users.get(UserList.getSelectedIndex());
        if (user.password.equals(StringCrypter.encrypt(Password.getText()))){
            WorkSpace.ws().currentUser(user);
            new M3DViewer().setVisible(true);
            setVisible(false);            
            }
        else
            MES.setText("Неверный пароль");
        }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        if(evt.getKeyCode()==10){//Enter key
            login();        
        }
    }//GEN-LAST:event_PasswordKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ws().closeApplication();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MES;
    private javax.swing.JPasswordField Password;
    private java.awt.Choice UserList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
