/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.cnc.settingsView;

import romanow.cnc.slicer.SliceRezult;

/**
 *
 * @author romanow
 */
public class StatisticPanel extends javax.swing.JPanel {

    /**
     * Creates new form StatisticPanel
     */
    public void setValues(SliceRezult statistic){
        LineCount.setText(""+statistic.lineCount());
        LineLength.setText(""+statistic.printLength());
        MoveProc.setText(""+statistic.moveProc());
        PrintTime.setText(""+statistic.printTime());
        SliceTime.setText(""+statistic.sliceTime());        
        }
    public StatisticPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        PrintTime = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        LineCount = new javax.swing.JTextField();
        LineLength = new javax.swing.JTextField();
        MoveProc = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        SliceTime = new javax.swing.JTextField();

        setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Статистика");
        add(jLabel10);
        jLabel10.setBounds(10, 10, 90, 20);

        jLabel16.setText("Время печати");
        add(jLabel16);
        jLabel16.setBounds(10, 150, 100, 14);

        jLabel25.setText("Линий");
        add(jLabel25);
        jLabel25.setBounds(10, 30, 80, 14);

        PrintTime.setEditable(false);
        PrintTime.setBackground(new java.awt.Color(200, 200, 200));
        add(PrintTime);
        PrintTime.setBounds(120, 140, 70, 25);

        jLabel26.setText("Длина  (м)");
        add(jLabel26);
        jLabel26.setBounds(10, 60, 80, 14);

        LineCount.setEditable(false);
        LineCount.setBackground(new java.awt.Color(200, 200, 200));
        add(LineCount);
        LineCount.setBounds(120, 20, 70, 25);

        LineLength.setEditable(false);
        LineLength.setBackground(new java.awt.Color(200, 200, 200));
        add(LineLength);
        LineLength.setBounds(120, 50, 70, 25);

        MoveProc.setEditable(false);
        MoveProc.setBackground(new java.awt.Color(200, 200, 200));
        add(MoveProc);
        MoveProc.setBounds(120, 80, 70, 25);

        jLabel27.setText("Холостой ход (%)");
        add(jLabel27);
        jLabel27.setBounds(10, 90, 100, 14);

        jLabel28.setText("Время слайсинга");
        add(jLabel28);
        jLabel28.setBounds(10, 120, 100, 14);

        SliceTime.setEditable(false);
        SliceTime.setBackground(new java.awt.Color(200, 200, 200));
        add(SliceTime);
        SliceTime.setBounds(120, 110, 70, 25);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LineCount;
    private javax.swing.JTextField LineLength;
    private javax.swing.JTextField MoveProc;
    private javax.swing.JTextField PrintTime;
    private javax.swing.JTextField SliceTime;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    // End of variables declaration//GEN-END:variables
}
