/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package romanow.cnc.view.panels;

import romanow.cnc.settings.WorkSpace;
import romanow.cnc.view.BasePanel;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Admin
 */
public class CNCPopup extends javax.swing.JFrame {
    Thread thread=null;
    /**
     * Creates new form Popup
     */
    public CNCPopup(String mes, final int delay) {
        setUndecorated(true);
        initComponents();
        WorkSpace ws = WorkSpace.ws();
        setBounds(300,200,(int)(ws.getScaleX()*560),(int)(ws.getScaleY()*105));
        BasePanel.setComponentsScale(this);
        setButtonText(Mes,mes,50);
        thread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(delay*1000);
                    } catch (InterruptedException e) {
                        }
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        dispose();
                        thread=null;
                        }
                    });
                }
            });
        thread.start();
        setVisible(true);
        toFront();
        }

    public static void setButtonText(JLabel label, String name, int size){
        name = name.replace("$","<br>");
        if (name.length()<=size) {
            label.setText("<html><center>&nbsp; &nbsp;"+name+"</html>");
            return;
        }
        int idx = name.substring(0,size).lastIndexOf(" ");
        String name2;
        if (idx==-1)
            name2 = "<html><center>&nbsp; &nbsp;"+name+"</html>";
        else
            name2 = "<html><center> &nbsp; &nbsp;"+name.substring(0,idx)+"<br> &nbsp; &nbsp;"+name.substring(idx+1)+"</html>";
        label.setText(name2);
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Mes = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable-mdpi/remove.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 30, 50, 40);

        Mes.setBackground(new java.awt.Color(255, 255, 255));
        Mes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Mes);
        Mes.setBounds(5, 5, 480, 95);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 0));
        jSeparator1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 0, 550, 3);

        jSeparator2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 100, 550, 3);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 0, 3, 100);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(550, 0, 3, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        synchronized (CNCPopup.this){
            if (thread!=null){
                thread=null;
                dispose();
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CNCPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CNCPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CNCPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CNCPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CNCPopup("a-a-a-a-a-a-a bbbbbbbbbbbbbbbbbbb ccccccccccccccccccccccccc ddddddddddddddddddddddddd eeeeeeeeeeeeeeeeeeeeeee",5);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mes;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
