/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.cnc.view;

import romanow.cnc.m3d.I_SettingsChanged;
import romanow.cnc.settings.*;
import romanow.cnc.utils.Events;
import romanow.cnc.slicer.SliceData;
import romanow.cnc.stl.MyAngle;
import romanow.cnc.utils.I_Notify;
import romanow.cnc.utils.Utils;
import romanow.cnc.Values;

import java.awt.*;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import romanow.cnc.settingsView.I_SettingsPanel;
import romanow.cnc.view.design.JCheckBoxButton;
import romanow.cnc.view.panels.DigitPanel;
import romanow.cnc.view.panels.I_RealValue;
import romanow.cnc.view.panels.KeyBoardPanel;

import javax.swing.*;

/**
 *
 * @author romanow
 */
public class GlobalSettingsPanel extends BasePanel  implements I_SettingsPanel{
    private Settings set;
    private I_SettingsChanged changed;
    private I_Notify notify;
    private boolean busy=false;
    private WorkSpace ws = WorkSpace.ws();
    private DecimalFormat df3;
    private DecimalFormat df2;
    private DecimalFormat df;
    private JCheckBoxButton autoScale;
    private JCheckBoxButton autoCenter;
    private JCheckBoxButton fullScreen;
    private JCheckBoxButton arcGCodeMode;
    private JCheckBoxButton moveOptimize;
    private JCheckBoxButton continuous;
    private JCheckBoxButton loopsWithSomeLineTypes;
    private JCheckBoxButton sendLoops;
    private JCheckBoxButton flateCircuitSlice;
    private JCheckBoxButton repairLoops;
    private FloatParameter shift = new FloatParameter(10);
    private IntParameter angle = new IntParameter(90);

    /**
     * Creates new form M3SSettings
     */
    public GlobalSettingsPanel(I_SettingsChanged changed0, Settings set0, I_Notify notify0) {
        super(null);
        initComponents();
        set = set0;
        changed = changed0;
        notify = notify0;
        }
    public GlobalSettingsPanel(CNCViewer base) {
        super(base);
        set = ws.global();
        notify = ws.getNotify();
        initComponents();
        setComponentsScale();
        busy = true;
        Mode2.removeAll();
        Mode2.addItem("Растр");
        Mode2.addItem("Клетки");
        Mode2.addItem("Случайная");
        Mode2.addItem("Фреза-1");
        busy = false;
        autoScale = new JCheckBoxButton(AutoScaleButton);
        autoCenter = new JCheckBoxButton(AutoCenterButton);
        fullScreen = new JCheckBoxButton(FullScreenButton);
        arcGCodeMode = new JCheckBoxButton(ARCGCodeModeButton);
        moveOptimize = new JCheckBoxButton(MoveOptimizeButton);
        continuous = new JCheckBoxButton(ContinuousButton);
        loopsWithSomeLineTypes = new JCheckBoxButton(LoopsWithSomeLineTypesButton);
        sendLoops = new JCheckBoxButton(SendLoopsButton);
        flateCircuitSlice = new JCheckBoxButton(FlateCircuitSliceButton);
        repairLoops = new JCheckBoxButton(RepairLoopsButton);
        }

    @Override
    public String getName() {
        return "Настройки";
    }

    @Override
    public int modeMask() {
        return Values.PanelGlobalSettings;
    }

    @Override
    public boolean modeEnabled() {
        return true;
    }

    @Override
    public void onActivate() {
        loadSettings();
        }

    @Override
    public void onDeactivate() {
        }

    @Override
    public void onClose() {
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MarkingFieldWidth = new javax.swing.JTextField();
        Z = new javax.swing.JTextField();
        PageServoOffsetsLeft = new javax.swing.JTextField();
        PageServoOffsetsTop = new javax.swing.JTextField();
        ScaleFactor = new javax.swing.JTextField();
        Z0_30 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        RotateButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        MarkingFieldHight = new javax.swing.JTextField();
        ANGLE = new javax.swing.JTextField();
        Zstart = new javax.swing.JTextField();
        Z0_2 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        Zfinish = new javax.swing.JTextField();
        Z0_18 = new javax.swing.JLabel();
        XYZ = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        PrintTime = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        LineCount = new javax.swing.JTextField();
        LineLength = new javax.swing.JTextField();
        MoveProc = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        SliceTime = new javax.swing.JTextField();
        ShiftButton = new javax.swing.JButton();
        SHIFT = new javax.swing.JTextField();
        XYZShift = new javax.swing.JComboBox<>();
        Z0_3 = new javax.swing.JLabel();
        Z0_4 = new javax.swing.JLabel();
        BlankHight = new javax.swing.JTextField();
        BlankWidth = new javax.swing.JTextField();
        CutterDiameter = new javax.swing.JTextField();
        Z0_5 = new javax.swing.JLabel();
        Z0_6 = new javax.swing.JLabel();
        StepMinus = new javax.swing.JTextField();
        VerticalStep = new javax.swing.JTextField();
        Z0_7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FillParametersOffset = new javax.swing.JTextField();
        Z2_2 = new javax.swing.JLabel();
        FillParametersAngle = new javax.swing.JTextField();
        Z2_3 = new javax.swing.JLabel();
        FillParametersFillCell = new javax.swing.JTextField();
        Z2_5 = new javax.swing.JLabel();
        FillingFlatness = new javax.swing.JTextField();
        FillParametersAngleInc = new javax.swing.JTextField();
        Z2_4 = new javax.swing.JLabel();
        Z2_6 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        Z2_1 = new javax.swing.JLabel();
        FillParametersRaster = new javax.swing.JTextField();
        Mode2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        Z0_8 = new javax.swing.JLabel();
        Z0_9 = new javax.swing.JLabel();
        WorkFrameZ = new javax.swing.JTextField();
        WorkFrameX = new javax.swing.JTextField();
        WorkFrameY = new javax.swing.JTextField();
        Z0_10 = new javax.swing.JLabel();
        Z0_11 = new javax.swing.JLabel();
        BaudRate = new javax.swing.JTextField();
        DeviceName = new javax.swing.JTextField();
        DevicePort = new javax.swing.JTextField();
        Z0_12 = new javax.swing.JLabel();
        Z0_13 = new javax.swing.JLabel();
        Z0_14 = new javax.swing.JLabel();
        DeviceTimeOut = new javax.swing.JTextField();
        BlankZ = new javax.swing.JTextField();
        Z0_15 = new javax.swing.JLabel();
        ZUp = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Z0_16 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        AutoScaleButton = new javax.swing.JButton();
        Z0_17 = new javax.swing.JLabel();
        AutoCenterButton = new javax.swing.JButton();
        Z0_19 = new javax.swing.JLabel();
        FullScreenButton = new javax.swing.JButton();
        Z0_20 = new javax.swing.JLabel();
        Z0_21 = new javax.swing.JLabel();
        Z0_22 = new javax.swing.JLabel();
        Z0_23 = new javax.swing.JLabel();
        Z0_24 = new javax.swing.JLabel();
        Z0_25 = new javax.swing.JLabel();
        Z0_26 = new javax.swing.JLabel();
        Z0_27 = new javax.swing.JLabel();
        ARCGCodeModeButton = new javax.swing.JButton();
        LoopsWithSomeLineTypesButton = new javax.swing.JButton();
        ContinuousButton = new javax.swing.JButton();
        MoveOptimizeButton = new javax.swing.JButton();
        SendLoopsButton = new javax.swing.JButton();
        FlateCircuitSliceButton = new javax.swing.JButton();
        RepairLoopsButton = new javax.swing.JButton();

        setBorder(new javax.swing.border.MatteBorder(null));
        setLayout(null);
        add(jLabel1);
        jLabel1.setBounds(30, 20, 34, 0);

        MarkingFieldWidth.setEditable(false);
        MarkingFieldWidth.setBackground(new java.awt.Color(200, 200, 200));
        MarkingFieldWidth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MarkingFieldWidth.setEnabled(false);
        add(MarkingFieldWidth);
        MarkingFieldWidth.setBounds(180, 30, 80, 30);

        Z.setEditable(false);
        Z.setBackground(new java.awt.Color(200, 200, 200));
        Z.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z.setEnabled(false);
        add(Z);
        Z.setBounds(180, 170, 80, 30);

        PageServoOffsetsLeft.setEditable(false);
        PageServoOffsetsLeft.setBackground(new java.awt.Color(200, 200, 200));
        PageServoOffsetsLeft.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PageServoOffsetsLeft.setEnabled(false);
        add(PageServoOffsetsLeft);
        PageServoOffsetsLeft.setBounds(180, 100, 80, 30);

        PageServoOffsetsTop.setEditable(false);
        PageServoOffsetsTop.setBackground(new java.awt.Color(200, 200, 200));
        PageServoOffsetsTop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PageServoOffsetsTop.setEnabled(false);
        add(PageServoOffsetsTop);
        PageServoOffsetsTop.setBounds(180, 135, 80, 30);

        ScaleFactor.setEditable(false);
        ScaleFactor.setBackground(new java.awt.Color(255, 255, 255));
        ScaleFactor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ScaleFactor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScaleFactor.setEnabled(false);
        ScaleFactor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScaleFactorMouseClicked(evt);
            }
        });
        ScaleFactor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ScaleFactorKeyPressed(evt);
            }
        });
        add(ScaleFactor);
        ScaleFactor.setBounds(180, 205, 80, 30);

        Z0_30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_30.setText("Масштаб модели");
        add(Z0_30);
        Z0_30.setBounds(10, 215, 130, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Станок / программа");
        add(jLabel10);
        jLabel10.setBounds(520, 10, 220, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Размер по X (мм)");
        add(jLabel11);
        jLabel11.setBounds(10, 40, 110, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Размер по Z (мм)");
        add(jLabel12);
        jLabel12.setBounds(10, 180, 110, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Смещ. X влево (мм)");
        add(jLabel14);
        jLabel14.setBounds(10, 110, 170, 20);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Смещ.  Y вверх (мм)");
        add(jLabel15);
        jLabel15.setBounds(10, 145, 140, 20);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Время фрезер.");
        add(jLabel16);
        jLabel16.setBounds(280, 180, 110, 20);

        RotateButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RotateButton.setText("Поворот");
        RotateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotateButtonActionPerformed(evt);
            }
        });
        add(RotateButton);
        RotateButton.setBounds(410, 530, 100, 30);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Размер по Y (мм)");
        add(jLabel22);
        jLabel22.setBounds(10, 75, 120, 20);

        MarkingFieldHight.setEditable(false);
        MarkingFieldHight.setBackground(new java.awt.Color(200, 200, 200));
        MarkingFieldHight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MarkingFieldHight.setEnabled(false);
        add(MarkingFieldHight);
        MarkingFieldHight.setBounds(180, 65, 80, 30);

        ANGLE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ANGLE.setText("90");
        ANGLE.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ANGLE.setEnabled(false);
        ANGLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ANGLEMouseClicked(evt);
            }
        });
        ANGLE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ANGLEKeyPressed(evt);
            }
        });
        add(ANGLE);
        ANGLE.setBounds(340, 530, 60, 30);

        Zstart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Zstart.setText("0");
        Zstart.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Zstart.setEnabled(false);
        Zstart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZstartMouseClicked(evt);
            }
        });
        add(Zstart);
        Zstart.setBounds(180, 240, 80, 30);

        Z0_2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_2.setText("Z поднятие фрезы  (мм) ");
        add(Z0_2);
        Z0_2.setBounds(10, 315, 160, 20);

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setText("Модель");
        add(jLabel46);
        jLabel46.setBounds(10, 10, 100, 20);
        add(jSeparator2);
        jSeparator2.setBounds(580, 152, 180, 0);
        add(jSeparator5);
        jSeparator5.setBounds(770, 330, 0, 3);

        Zfinish.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Zfinish.setText("0");
        Zfinish.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Zfinish.setEnabled(false);
        Zfinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZfinishMouseClicked(evt);
            }
        });
        add(Zfinish);
        Zfinish.setBounds(180, 275, 80, 30);

        Z0_18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_18.setText("Автоцентрирование");
        add(Z0_18);
        Z0_18.setBounds(10, 610, 170, 20);

        XYZ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        XYZ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "Y", "Z" }));
        add(XYZ);
        XYZ.setBounds(280, 530, 50, 30);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Линий");
        add(jLabel25);
        jLabel25.setBounds(280, 45, 80, 20);

        PrintTime.setEditable(false);
        PrintTime.setBackground(new java.awt.Color(200, 200, 200));
        PrintTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PrintTime.setEnabled(false);
        add(PrintTime);
        PrintTime.setBounds(400, 170, 80, 30);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Длина  (м)");
        add(jLabel26);
        jLabel26.setBounds(280, 75, 110, 20);

        LineCount.setEditable(false);
        LineCount.setBackground(new java.awt.Color(200, 200, 200));
        LineCount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LineCount.setEnabled(false);
        add(LineCount);
        LineCount.setBounds(400, 30, 80, 30);

        LineLength.setEditable(false);
        LineLength.setBackground(new java.awt.Color(200, 200, 200));
        LineLength.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LineLength.setEnabled(false);
        add(LineLength);
        LineLength.setBounds(400, 65, 80, 30);

        MoveProc.setEditable(false);
        MoveProc.setBackground(new java.awt.Color(200, 200, 200));
        MoveProc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MoveProc.setEnabled(false);
        add(MoveProc);
        MoveProc.setBounds(400, 100, 80, 30);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Холостой ход (%)");
        add(jLabel27);
        jLabel27.setBounds(280, 110, 120, 20);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Время слайсинга");
        add(jLabel28);
        jLabel28.setBounds(280, 145, 120, 20);

        SliceTime.setEditable(false);
        SliceTime.setBackground(new java.awt.Color(200, 200, 200));
        SliceTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SliceTime.setEnabled(false);
        add(SliceTime);
        SliceTime.setBounds(400, 135, 80, 30);

        ShiftButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ShiftButton.setText("Сдвиг");
        ShiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShiftButtonActionPerformed(evt);
            }
        });
        add(ShiftButton);
        ShiftButton.setBounds(410, 490, 100, 30);

        SHIFT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SHIFT.setText("10.0");
        SHIFT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        SHIFT.setEnabled(false);
        SHIFT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SHIFTMouseClicked(evt);
            }
        });
        SHIFT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SHIFTKeyPressed(evt);
            }
        });
        add(SHIFT);
        SHIFT.setBounds(340, 490, 60, 30);

        XYZShift.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        XYZShift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "Y", "Z" }));
        add(XYZShift);
        XYZShift.setBounds(280, 490, 50, 30);

        Z0_3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_3.setText("Z начальное (мм) ");
        add(Z0_3);
        Z0_3.setBounds(10, 250, 130, 20);

        Z0_4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_4.setText("Тайм-аут (c)");
        add(Z0_4);
        Z0_4.setBounds(520, 250, 130, 20);

        BlankHight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BlankHight.setText("0");
        BlankHight.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        BlankHight.setEnabled(false);
        BlankHight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BlankHightMouseClicked(evt);
            }
        });
        add(BlankHight);
        BlankHight.setBounds(180, 380, 80, 30);

        BlankWidth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BlankWidth.setText("0");
        BlankWidth.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        BlankWidth.setEnabled(false);
        BlankWidth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BlankWidthMouseClicked(evt);
            }
        });
        add(BlankWidth);
        BlankWidth.setBounds(180, 345, 80, 30);

        CutterDiameter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CutterDiameter.setText("0");
        CutterDiameter.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CutterDiameter.setEnabled(false);
        CutterDiameter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CutterDiameterMouseClicked(evt);
            }
        });
        add(CutterDiameter);
        CutterDiameter.setBounds(180, 450, 80, 30);

        Z0_5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_5.setText("Размер заготовки Z(мм)");
        add(Z0_5);
        Z0_5.setBounds(10, 425, 170, 20);

        Z0_6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_6.setText("Диаметр фрезы (мм)");
        add(Z0_6);
        Z0_6.setBounds(10, 460, 170, 20);

        StepMinus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StepMinus.setText("0");
        StepMinus.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        StepMinus.setEnabled(false);
        StepMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StepMinusMouseClicked(evt);
            }
        });
        add(StepMinus);
        StepMinus.setBounds(180, 486, 80, 30);

        VerticalStep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VerticalStep.setText("0");
        VerticalStep.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        VerticalStep.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        VerticalStep.setEnabled(false);
        VerticalStep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerticalStepMouseClicked(evt);
            }
        });
        add(VerticalStep);
        VerticalStep.setBounds(180, 520, 80, 30);

        Z0_7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_7.setText("Коррекция шага (мм)");
        add(Z0_7);
        Z0_7.setBounds(10, 495, 170, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Фактура");
        add(jLabel2);
        jLabel2.setBounds(280, 245, 110, 20);

        FillParametersOffset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FillParametersOffset.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        FillParametersOffset.setEnabled(false);
        FillParametersOffset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FillParametersOffsetMouseClicked(evt);
            }
        });
        add(FillParametersOffset);
        FillParametersOffset.setBounds(430, 315, 80, 30);

        Z2_2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z2_2.setText("Смещение клетки (мм)");
        add(Z2_2);
        Z2_2.setBounds(280, 320, 160, 20);

        FillParametersAngle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FillParametersAngle.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        FillParametersAngle.setEnabled(false);
        FillParametersAngle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FillParametersAngleMouseClicked(evt);
            }
        });
        add(FillParametersAngle);
        FillParametersAngle.setBounds(430, 350, 80, 30);

        Z2_3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z2_3.setText("Угол начальный (°)");
        add(Z2_3);
        Z2_3.setBounds(280, 355, 150, 20);

        FillParametersFillCell.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FillParametersFillCell.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        FillParametersFillCell.setEnabled(false);
        FillParametersFillCell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FillParametersFillCellMouseClicked(evt);
            }
        });
        add(FillParametersFillCell);
        FillParametersFillCell.setBounds(430, 420, 80, 30);

        Z2_5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z2_5.setText("Размер клетки (мм)");
        add(Z2_5);
        Z2_5.setBounds(280, 425, 140, 20);

        FillingFlatness.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FillingFlatness.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        FillingFlatness.setEnabled(false);
        FillingFlatness.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FillingFlatnessMouseClicked(evt);
            }
        });
        add(FillingFlatness);
        FillingFlatness.setBounds(430, 455, 80, 30);

        FillParametersAngleInc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FillParametersAngleInc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        FillParametersAngleInc.setEnabled(false);
        FillParametersAngleInc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FillParametersAngleIncMouseClicked(evt);
            }
        });
        add(FillParametersAngleInc);
        FillParametersAngleInc.setBounds(430, 385, 80, 30);

        Z2_4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z2_4.setText("Приращение угла (°)");
        add(Z2_4);
        Z2_4.setBounds(280, 390, 150, 20);

        Z2_6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z2_6.setText("Сглаживание (мм)");
        add(Z2_6);
        Z2_6.setBounds(280, 460, 140, 20);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setText("Слайсинг");
        add(jLabel39);
        jLabel39.setBounds(280, 215, 80, 20);

        Z2_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z2_1.setText("Шаг растра (мм)");
        add(Z2_1);
        Z2_1.setBounds(280, 285, 120, 20);

        FillParametersRaster.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FillParametersRaster.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        FillParametersRaster.setEnabled(false);
        FillParametersRaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FillParametersRasterMouseClicked(evt);
            }
        });
        add(FillParametersRaster);
        FillParametersRaster.setBounds(430, 280, 80, 30);

        Mode2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Mode2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Mode2ItemStateChanged(evt);
            }
        });
        add(Mode2);
        Mode2.setBounds(380, 240, 130, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Статистика");
        add(jLabel13);
        jLabel13.setBounds(280, 10, 100, 20);

        Z0_8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_8.setText("Размер заготовки X(мм)");
        add(Z0_8);
        Z0_8.setBounds(10, 355, 170, 20);

        Z0_9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_9.setText("Размер стола X(мм)");
        add(Z0_9);
        Z0_9.setBounds(520, 35, 170, 20);

        WorkFrameZ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        WorkFrameZ.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        WorkFrameZ.setEnabled(false);
        WorkFrameZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WorkFrameZMouseClicked(evt);
            }
        });
        WorkFrameZ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                WorkFrameZKeyPressed(evt);
            }
        });
        add(WorkFrameZ);
        WorkFrameZ.setBounds(660, 100, 80, 30);

        WorkFrameX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        WorkFrameX.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        WorkFrameX.setEnabled(false);
        WorkFrameX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WorkFrameXMouseClicked(evt);
            }
        });
        WorkFrameX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                WorkFrameXKeyPressed(evt);
            }
        });
        add(WorkFrameX);
        WorkFrameX.setBounds(660, 30, 80, 30);

        WorkFrameY.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        WorkFrameY.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        WorkFrameY.setEnabled(false);
        WorkFrameY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WorkFrameYMouseClicked(evt);
            }
        });
        WorkFrameY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                WorkFrameYKeyPressed(evt);
            }
        });
        add(WorkFrameY);
        WorkFrameY.setBounds(660, 65, 80, 30);

        Z0_10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_10.setText("Размер стола Y(мм)");
        add(Z0_10);
        Z0_10.setBounds(520, 70, 170, 20);

        Z0_11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_11.setText("Размер стола Z(мм)");
        add(Z0_11);
        Z0_11.setBounds(520, 105, 170, 20);

        BaudRate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BaudRate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        BaudRate.setEnabled(false);
        BaudRate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BaudRateMouseClicked(evt);
            }
        });
        BaudRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BaudRateKeyPressed(evt);
            }
        });
        add(BaudRate);
        BaudRate.setBounds(660, 210, 80, 30);

        DeviceName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeviceName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DeviceName.setEnabled(false);
        DeviceName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeviceNameMouseClicked(evt);
            }
        });
        DeviceName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DeviceNameKeyPressed(evt);
            }
        });
        add(DeviceName);
        DeviceName.setBounds(660, 135, 80, 30);

        DevicePort.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DevicePort.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DevicePort.setEnabled(false);
        DevicePort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DevicePortMouseClicked(evt);
            }
        });
        DevicePort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DevicePortKeyPressed(evt);
            }
        });
        add(DevicePort);
        DevicePort.setBounds(660, 170, 80, 30);

        Z0_12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_12.setText("Устройство");
        add(Z0_12);
        Z0_12.setBounds(520, 140, 150, 20);

        Z0_13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_13.setText("Номер (порт)");
        add(Z0_13);
        Z0_13.setBounds(520, 175, 150, 20);

        Z0_14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_14.setText("Скорость (бит/c)");
        add(Z0_14);
        Z0_14.setBounds(520, 215, 150, 20);

        DeviceTimeOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeviceTimeOut.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DeviceTimeOut.setEnabled(false);
        DeviceTimeOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeviceTimeOutMouseClicked(evt);
            }
        });
        DeviceTimeOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DeviceTimeOutKeyPressed(evt);
            }
        });
        add(DeviceTimeOut);
        DeviceTimeOut.setBounds(660, 245, 80, 30);

        BlankZ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BlankZ.setText("0");
        BlankZ.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        BlankZ.setEnabled(false);
        BlankZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BlankZMouseClicked(evt);
            }
        });
        add(BlankZ);
        BlankZ.setBounds(180, 415, 80, 30);

        Z0_15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_15.setText("Размер заготовки Y(мм)");
        add(Z0_15);
        Z0_15.setBounds(10, 390, 170, 20);

        ZUp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ZUp.setText("0");
        ZUp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ZUp.setEnabled(false);
        ZUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZUpMouseClicked(evt);
            }
        });
        add(ZUp);
        ZUp.setBounds(180, 310, 80, 30);
        add(jSeparator1);
        jSeparator1.setBounds(270, 207, 220, 3);

        Z0_16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_16.setText("Z конечное (мм) ");
        add(Z0_16);
        Z0_16.setBounds(10, 280, 120, 20);
        add(jSeparator3);
        jSeparator3.setBounds(510, 330, 240, 10);

        AutoScaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoScaleButtonActionPerformed(evt);
            }
        });
        add(AutoScaleButton);
        AutoScaleButton.setBounds(180, 560, 50, 40);

        Z0_17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_17.setText("Шаг по вертикали (мм)");
        add(Z0_17);
        Z0_17.setBounds(10, 530, 170, 20);

        AutoCenterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoCenterButtonActionPerformed(evt);
            }
        });
        add(AutoCenterButton);
        AutoCenterButton.setBounds(180, 605, 50, 40);

        Z0_19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_19.setText("Автомасштабирование");
        add(Z0_19);
        Z0_19.setBounds(10, 570, 170, 20);

        FullScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullScreenButtonActionPerformed(evt);
            }
        });
        add(FullScreenButton);
        FullScreenButton.setBounds(660, 280, 50, 40);

        Z0_20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_20.setText("Полный экран");
        add(Z0_20);
        Z0_20.setBounds(520, 290, 120, 20);

        Z0_21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_21.setText("G code: круговая интерполяция");
        add(Z0_21);
        Z0_21.setBounds(520, 350, 220, 20);

        Z0_22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_22.setText("Оптимизация перемещений");
        add(Z0_22);
        Z0_22.setBounds(520, 400, 200, 20);

        Z0_23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_23.setText("Непрерывная штриховка / Зигзаг");
        add(Z0_23);
        Z0_23.setBounds(520, 440, 220, 20);

        Z0_24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_24.setText("Оконтуривание");
        add(Z0_24);
        Z0_24.setBounds(520, 480, 120, 20);

        Z0_25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_25.setText("Слайсинг плоских контуров");
        add(Z0_25);
        Z0_25.setBounds(520, 530, 200, 20);

        Z0_26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_26.setText("Принудительно замыкать контуры");
        add(Z0_26);
        Z0_26.setBounds(520, 570, 240, 20);

        Z0_27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Z0_27.setText("Контуры из отрезков одного типа");
        add(Z0_27);
        Z0_27.setBounds(520, 620, 220, 20);

        ARCGCodeModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ARCGCodeModeButtonActionPerformed(evt);
            }
        });
        add(ARCGCodeModeButton);
        ARCGCodeModeButton.setBounds(750, 340, 50, 40);

        LoopsWithSomeLineTypesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoopsWithSomeLineTypesButtonActionPerformed(evt);
            }
        });
        add(LoopsWithSomeLineTypesButton);
        LoopsWithSomeLineTypesButton.setBounds(750, 610, 50, 40);

        ContinuousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuousButtonActionPerformed(evt);
            }
        });
        add(ContinuousButton);
        ContinuousButton.setBounds(750, 430, 50, 40);

        MoveOptimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveOptimizeButtonActionPerformed(evt);
            }
        });
        add(MoveOptimizeButton);
        MoveOptimizeButton.setBounds(750, 385, 50, 40);

        SendLoopsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendLoopsButtonActionPerformed(evt);
            }
        });
        add(SendLoopsButton);
        SendLoopsButton.setBounds(750, 475, 50, 40);

        FlateCircuitSliceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlateCircuitSliceButtonActionPerformed(evt);
            }
        });
        add(FlateCircuitSliceButton);
        FlateCircuitSliceButton.setBounds(750, 520, 50, 40);

        RepairLoopsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepairLoopsButtonActionPerformed(evt);
            }
        });
        add(RepairLoopsButton);
        RepairLoopsButton.setBounds(750, 565, 50, 40);
    }// </editor-fold>//GEN-END:initComponents
    public boolean loadSettings(){
        try {
            set = ws.global();
            busy = true;
            set.setNotNull();
            DecimalFormatSymbols dfs = new DecimalFormatSymbols(Locale.US);
            df = new DecimalFormat("0.000", dfs);
            df2 = new DecimalFormat("0.00", dfs);
            df3 = new DecimalFormat("000.0", dfs);
            MarkingFieldHight.setText(df2.format(set.model.ModelHight.getVal()));
            MarkingFieldWidth.setText(df2.format(set.model.ModelWidth.getVal()));
            BlankHight.setText(df2.format(set.model.BlankHight.getVal()*2));
            BlankWidth.setText(df2.format(set.model.BlankWidth.getVal()*2));
            BlankZ.setText(df2.format(set.model.BlankZ.getVal()));
            CutterDiameter.setText(df2.format(set.model.CutterDiameter.getVal()));
            StepMinus.setText(df2.format(set.model.StepMinus.getVal()));
            VerticalStep.setText(df2.format(set.model.VerticalStep.getVal()));
            Z.setText(df2.format(set.model.ModelZ.getVal()));
            Zstart.setText(df2.format(set.model.ZStart.getVal()));
            Zfinish.setText(df2.format(set.model.ZFinish.getVal()));
            ZUp.setText(df2.format(set.model.ZUp.getVal()));
            PageServoOffsetsLeft.setText(df2.format(set.model.PageServoOffsetsLeft.getVal()));
            PageServoOffsetsTop.setText(df2.format(set.model.PageServoOffsetsTop.getVal()));
            ScaleFactor.setText(df.format(set.model.ScaleFactor.getVal()));
            LineCount.setText(""+set.statistic.LineCount.getVal());
            LineLength.setText(set.statistic.printLength());
            MoveProc.setText(""+set.statistic.moveProc());
            PrintTime.setText(set.statistic.printTime());
            SliceTime.setText(set.statistic.sliceTime());
            //------------------------------------------------------------------------
            //VerticalStep.setText(df.format(set.slice.VerticalStep.getVal()));
            Mode2.setSelectedIndex(set.slice.Mode.getVal());
            FillParametersRaster.setText(df.format(set.slice.FillParametersRaster.getVal()));
            FillParametersOffset.setText(df.format(set.slice.FillParametersOffset.getVal()));
            FillParametersAngle.setText(df.format(set.slice.FillParametersAngle.getVal()));
            FillParametersAngleInc.setText(df.format(set.slice.FillParametersAngleInc.getVal()));
            FillParametersFillCell.setText(df.format(set.slice.FillParametersFillCell.getVal()));
            FillingFlatness.setText(df.format(set.slice.FillingFlatness.getVal()));
            moveOptimize.setSelected(set.slice.MoveOptimize.getVal());
            sendLoops.setSelected(set.slice.SendLoops.getVal());
            continuous.setSelected(set.slice.FillContinuous.getVal());
            flateCircuitSlice.setSelected(set.slice.FlateCircuitSlice.getVal());
            ContinuousButton.setVisible(moveOptimize.isSelected());
            Z0_23.setVisible(moveOptimize.isSelected());
            repairLoops.setSelected(set.slice.RepairLoops.getVal());
            loopsWithSomeLineTypes.setSelected(set.slice.LoopsWithSomeLineTypes.getVal());
            WorkFrameX.setText(df2.format(set.mashine.WorkFrameX.getVal()));
            WorkFrameY.setText(df2.format(set.mashine.WorkFrameY.getVal()));
            WorkFrameZ.setText(df2.format(set.mashine.WorkFrameZ.getVal()));
            autoScale.setSelected(set.model.AutoScale.getVal());
            autoCenter.setSelected(set.model.AutoCenter.getVal());
            arcGCodeMode.setSelected(set.slice.ARCGCodeMode.getVal());
            DeviceName.setText(set.mashine.DeviceName.getVal());
            DevicePort.setText(""+set.mashine.DeviceNum.getVal());
            BaudRate.setText(""+set.mashine.BaudRate.getVal());
            DeviceTimeOut.setText(""+set.mashine.DeviceTimeOut.getVal());
            fullScreen.setSelected(set.fullScreen);
        } catch (Exception ee){
                notify.notify(Values.error, Utils.createFatalMessage(ee,5));
                busy = false;
                return false; 
                }
            busy=false;
        return true;
        }

    public boolean saveSettings(String par){
        try {
            Settings set = ws.local();
            set.model.ZStart.setVal(Float.parseFloat(Zstart.getText()));
            set.model.ZFinish.setVal(Float.parseFloat(Zfinish.getText()));
            set.model.ZUp.setVal(Float.parseFloat(ZUp.getText()));
            set.model.BlankWidth.setVal(Float.parseFloat(BlankWidth.getText())/2);
            set.model.BlankHight.setVal(Float.parseFloat(BlankHight.getText())/2);
            set.model.BlankZ.setVal(Float.parseFloat(BlankZ.getText()));
            set.model.CutterDiameter.setVal(Float.parseFloat(CutterDiameter.getText()));
            set.model.StepMinus.setVal(Float.parseFloat(StepMinus.getText()));
            set.model.VerticalStep.setVal(Float.parseFloat(VerticalStep.getText()));
            set.model.AutoCenter.setVal(autoCenter.isSelected());
            set.model.AutoScale.setVal(autoScale.isSelected());
            //---------------------------------------------------------------------------------------
            set.slice.Mode.setVal(Mode2.getSelectedIndex());
            set.slice.FillParametersRaster.setVal(Float.parseFloat(FillParametersRaster.getText()));
            set.slice.FillParametersOffset.setVal(Float.parseFloat(FillParametersOffset.getText()));
            set.slice.FillParametersAngle.setVal(Float.parseFloat(FillParametersAngle.getText()));
            set.slice.FillParametersAngleInc.setVal(Float.parseFloat(FillParametersAngleInc.getText()));
            set.slice.FillParametersFillCell.setVal(Float.parseFloat(FillParametersFillCell.getText()));
            set.slice.FillingFlatness.setVal(Float.parseFloat(FillingFlatness.getText()));
            set.slice.MoveOptimize.setVal(moveOptimize.isSelected());
            set.slice.SendLoops.setVal(sendLoops.isSelected());
            set.slice.FlateCircuitSlice.setVal(flateCircuitSlice.isSelected());
            set.slice.FillContinuous.setVal(continuous.isSelected());
            set.slice.RepairLoops.setVal(repairLoops.isSelected());
            set.slice.LoopsWithSomeLineTypes.setVal(loopsWithSomeLineTypes.isSelected());
            set.slice.ARCGCodeMode.setVal(arcGCodeMode.isSelected());
            set.mashine.BaudRate.setVal(Integer.parseInt(BaudRate.getText()));
            set.mashine.DeviceName.setVal(DeviceName.getText());
            set.mashine.DeviceNum.setVal(Integer.parseInt(DevicePort.getText()));
            set.fullScreen = fullScreen.isSelected();
            sendEvent(Events.Settings,0,0,null,null);
            if (par!=null)
                notify.notify(Values.info,"Изменен параметр: "+par);
            } catch (Exception ee){
                notify.notify(Values.error,ee.toString());
                return false; 
                }
        return true;
        }

    @Override
    public void refresh() {
        }

    @Override
    public void onEvent(int code, int par1, long par2, String par3, Object oo) {
        }
    @Override
    public void shutDown() {
        }


    private void RotateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotateButtonActionPerformed
        double angle;
        try {
            angle = Double.parseDouble(ANGLE.getText())*Math.PI/180;
        } catch(Exception ee){
            notify.notify(Values.error,"Недопустимое значение угла");
            return;
        }
        ws.model().rotate(XYZ.getSelectedIndex(),new MyAngle(angle),notify);
        ws.model().shiftToCenter();
        ws.data(new SliceData());
        Settings set = ws.local();
        ws.model().saveModelDimensions();
        set.setZStartFinish();
        loadSettings();
        notify.log(String.format("Поворот %2s %s",(String)XYZ.getSelectedItem(),ANGLE.getText()));
        ws.sendEvent(Events.Rotate);
    }//GEN-LAST:event_RotateButtonActionPerformed

    private void ShiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShiftButtonActionPerformed
        double shift;
        try {
            shift = Double.parseDouble(SHIFT.getText());
        } catch(Exception ee){
            notify.notify(Values.error,"Недопустимое значение сдвига");
            return;
            }
        //shift/=;
        ws.model().shift(XYZShift.getSelectedIndex(),shift);
        ws.data(new SliceData());
        Settings set = ws.local();
        ws.model().saveModelDimensions();
        set.setZStartFinish();
        loadSettings();
        notify.log(String.format("Сдвиг %2s %s",(String)XYZShift.getSelectedItem(),SHIFT.getText()));
        ws.sendEvent(Events.Rotate);

    }//GEN-LAST:event_ShiftButtonActionPerformed

    private void ANGLEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ANGLEKeyPressed
        if(evt.getKeyCode()!=10) return;
        double angle;
        try {
            angle = Double.parseDouble(ANGLE.getText())*Math.PI/180;
        } catch(Exception ee){
            notify.notify(Values.error,"Недопустимое значение угла");
            return;
        }
        ws.model().rotate(XYZ.getSelectedIndex(),new MyAngle(angle),notify);
        ws.model().shiftToCenter();
        ws.data(new SliceData());
        Settings set = ws.local();
        ws.model().saveModelDimensions();
        set.setZStartFinish();
        loadSettings();
        notify.log(String.format("Поворот %2s %s",(String)XYZ.getSelectedItem(),ANGLE.getText()));
        ws.sendEvent(Events.Rotate);
    }//GEN-LAST:event_ANGLEKeyPressed

    private void SHIFTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SHIFTKeyPressed
        if(evt.getKeyCode()!=10) return;
        double shift;
        try {
            shift = Double.parseDouble(SHIFT.getText());
        } catch(Exception ee){
            notify.notify(Values.error,"Недопустимое значение сдвига");
            return;
        }
        //shift/=;
        ws.model().shift(XYZShift.getSelectedIndex(),shift);
        ws.data(new SliceData());
        Settings set = ws.local();
        ws.model().saveModelDimensions();
        set.setZStartFinish();
        loadSettings();
        notify.log(String.format("Сдвиг %2s %s",(String)XYZShift.getSelectedItem(),SHIFT.getText()));
        ws.sendEvent(Events.Rotate);
    }//GEN-LAST:event_SHIFTKeyPressed

    private void Mode2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Mode2ItemStateChanged
        if (busy) return;
        set.slice.Mode.setVal(Mode2.getSelectedIndex());
        Utils.viewUpdate(Mode2,true);
    }//GEN-LAST:event_Mode2ItemStateChanged

    private void WorkFrameZKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WorkFrameZKeyPressed
        Utils.saveKeyPressed(evt,set.mashine.WorkFrameZ,set,notify);
    }//GEN-LAST:event_WorkFrameZKeyPressed

    private void WorkFrameXKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WorkFrameXKeyPressed
        Utils.saveKeyPressed(evt,set.mashine.WorkFrameX,set,notify);
    }//GEN-LAST:event_WorkFrameXKeyPressed

    private void WorkFrameYKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WorkFrameYKeyPressed
        Utils.saveKeyPressed(evt,set.mashine.WorkFrameY,set,notify);
    }//GEN-LAST:event_WorkFrameYKeyPressed

    private void ScaleFactorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ScaleFactorKeyPressed
        Utils.saveKeyPressed(evt,set.model.ScaleFactor,set,notify);
    }//GEN-LAST:event_ScaleFactorKeyPressed

    private void BaudRateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BaudRateKeyPressed
        Utils.saveKeyPressed(evt,set.mashine.BaudRate,set,notify);
    }//GEN-LAST:event_BaudRateKeyPressed

    private void DeviceNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DeviceNameKeyPressed
        Utils.saveKeyPressed(evt,set.mashine.DeviceName,set,notify);
    }//GEN-LAST:event_DeviceNameKeyPressed

    private void DevicePortKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DevicePortKeyPressed
        Utils.saveKeyPressed(evt,set.mashine.DeviceNum,set,notify);
    }//GEN-LAST:event_DevicePortKeyPressed

    private void DeviceTimeOutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DeviceTimeOutKeyPressed
        Utils.saveKeyPressed(evt,set.mashine.DeviceTimeOut,set,notify);
    }//GEN-LAST:event_DeviceTimeOutKeyPressed



    private void ZstartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZstartMouseClicked
        updateField(Z0_3.getText(),Zstart,set.model.ZStart);
    }//GEN-LAST:event_ZstartMouseClicked

    private void VerticalStepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerticalStepMouseClicked
        updateField(Z0_17.getText(),VerticalStep,set.model.VerticalStep);
    }//GEN-LAST:event_VerticalStepMouseClicked

    private void ZfinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZfinishMouseClicked
        updateField(Z0_16.getText(),Zfinish,set.model.ZFinish);
    }//GEN-LAST:event_ZfinishMouseClicked

    private void ZUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZUpMouseClicked
        updateField(Z0_2.getText(),ZUp,set.model.ZUp);
    }//GEN-LAST:event_ZUpMouseClicked

    private void BlankWidthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlankWidthMouseClicked
        updateField(Z0_8.getText(),BlankWidth,set.model.BlankWidth,2.0);
    }//GEN-LAST:event_BlankWidthMouseClicked

    private void BlankHightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlankHightMouseClicked
        updateField(Z0_15.getText(),BlankHight,set.model.BlankHight,2.0);
    }//GEN-LAST:event_BlankHightMouseClicked

    private void BlankZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlankZMouseClicked
        updateField(Z0_5.getText(),BlankZ,set.model.BlankZ);
    }//GEN-LAST:event_BlankZMouseClicked

    private void CutterDiameterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CutterDiameterMouseClicked
        updateField(Z0_6.getText(),CutterDiameter,set.model.CutterDiameter);
    }//GEN-LAST:event_CutterDiameterMouseClicked

    private void StepMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StepMinusMouseClicked
        updateField(Z0_7.getText(),StepMinus,set.model.StepMinus);
    }//GEN-LAST:event_StepMinusMouseClicked

    private void FillParametersRasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FillParametersRasterMouseClicked
        updateField(Z2_1.getText(),FillParametersRaster,set.slice.FillParametersRaster);
    }//GEN-LAST:event_FillParametersRasterMouseClicked

    private void FillParametersOffsetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FillParametersOffsetMouseClicked
        updateField(Z2_2.getText(),FillParametersOffset,set.slice.FillParametersOffset);
    }//GEN-LAST:event_FillParametersOffsetMouseClicked

    private void FillParametersAngleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FillParametersAngleMouseClicked
        updateField(Z2_3.getText(),FillParametersAngle,set.slice.FillParametersAngle);
    }//GEN-LAST:event_FillParametersAngleMouseClicked

    private void FillParametersAngleIncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FillParametersAngleIncMouseClicked
        updateField(Z2_4.getText(),FillParametersAngleInc,set.slice.FillParametersAngleInc);
    }//GEN-LAST:event_FillParametersAngleIncMouseClicked

    private void FillParametersFillCellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FillParametersFillCellMouseClicked
        updateField(Z2_5.getText(),FillParametersFillCell,set.slice.FillParametersFillCell);
    }//GEN-LAST:event_FillParametersFillCellMouseClicked

    private void FillingFlatnessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FillingFlatnessMouseClicked
        updateField(Z2_6.getText(),FillingFlatness,set.slice.FillingFlatness);
    }//GEN-LAST:event_FillingFlatnessMouseClicked

    private void WorkFrameXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WorkFrameXMouseClicked
        updateField(Z0_9.getText(),WorkFrameX,set.mashine.WorkFrameX);
    }//GEN-LAST:event_WorkFrameXMouseClicked

    private void WorkFrameYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WorkFrameYMouseClicked
        updateField(Z0_10.getText(),WorkFrameY,set.mashine.WorkFrameY);
    }//GEN-LAST:event_WorkFrameYMouseClicked

    private void WorkFrameZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WorkFrameZMouseClicked
        updateField(Z0_11.getText(),WorkFrameZ,set.mashine.WorkFrameZ);
    }//GEN-LAST:event_WorkFrameZMouseClicked

    private void DeviceNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeviceNameMouseClicked
        updateField(Z0_12.getText(),DeviceName,set.mashine.DeviceName);
    }//GEN-LAST:event_DeviceNameMouseClicked

    private void DevicePortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DevicePortMouseClicked
        updateField(Z0_13.getText(),DevicePort,set.mashine.DeviceNum);
    }//GEN-LAST:event_DevicePortMouseClicked

    private void BaudRateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaudRateMouseClicked
        updateField(Z0_14.getText(),BaudRate,set.mashine.BaudRate);
    }//GEN-LAST:event_BaudRateMouseClicked

    private void DeviceTimeOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeviceTimeOutMouseClicked
        updateField(Z0_4.getText(),DeviceTimeOut,set.mashine.DeviceTimeOut);
    }//GEN-LAST:event_DeviceTimeOutMouseClicked

    private void AutoScaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoScaleButtonActionPerformed
        updateField(Z0_19.getText(),autoScale,set.model.AutoScale);
    }//GEN-LAST:event_AutoScaleButtonActionPerformed

    private void AutoCenterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoCenterButtonActionPerformed
        updateField(Z0_18.getText(),autoCenter,set.model.AutoCenter);
    }//GEN-LAST:event_AutoCenterButtonActionPerformed

    private void FullScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullScreenButtonActionPerformed
        fullScreen.itemStateChanged();
        WorkSpace ws = WorkSpace.ws();
        ws.getNotify().notify(Values.info,"Изменен параметр: "+Z0_20.getText()+"="+fullScreen.isSelected());
        ws.global().fullScreen = fullScreen.isSelected();
        ws.saveSettings();
    }//GEN-LAST:event_FullScreenButtonActionPerformed

    private void ARCGCodeModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ARCGCodeModeButtonActionPerformed
        updateField(Z0_21.getText(),arcGCodeMode,set.slice.ARCGCodeMode);
    }//GEN-LAST:event_ARCGCodeModeButtonActionPerformed

    private void LoopsWithSomeLineTypesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoopsWithSomeLineTypesButtonActionPerformed
        updateField(Z0_27.getText(),loopsWithSomeLineTypes,set.slice.LoopsWithSomeLineTypes);
    }//GEN-LAST:event_LoopsWithSomeLineTypesButtonActionPerformed

    private void ContinuousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuousButtonActionPerformed
        updateField(Z0_23.getText(),continuous,set.slice.FillContinuous);
    }//GEN-LAST:event_ContinuousButtonActionPerformed

    private void MoveOptimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveOptimizeButtonActionPerformed
        updateField(Z0_22.getText(),moveOptimize,set.slice.MoveOptimize);
        ContinuousButton.setVisible(moveOptimize.isSelected());
        Z0_23.setVisible(moveOptimize.isSelected());
    }//GEN-LAST:event_MoveOptimizeButtonActionPerformed

    private void SendLoopsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendLoopsButtonActionPerformed
        updateField(Z0_24.getText(),sendLoops,set.slice.SendLoops);
    }//GEN-LAST:event_SendLoopsButtonActionPerformed

    private void FlateCircuitSliceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlateCircuitSliceButtonActionPerformed
        updateField(Z0_25.getText(),flateCircuitSlice,set.slice.FlateCircuitSlice);
    }//GEN-LAST:event_FlateCircuitSliceButtonActionPerformed

    private void RepairLoopsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepairLoopsButtonActionPerformed
        updateField(Z0_26.getText(),repairLoops,set.slice.RepairLoops);
    }//GEN-LAST:event_RepairLoopsButtonActionPerformed

    private void SHIFTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SHIFTMouseClicked
        updateField(ShiftButton.getText(),SHIFT,shift);
    }//GEN-LAST:event_SHIFTMouseClicked

    private void ANGLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ANGLEMouseClicked
        updateField(RotateButton.getText(),ANGLE,angle);
    }//GEN-LAST:event_ANGLEMouseClicked

    private void ScaleFactorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScaleFactorMouseClicked
        updateField(Z0_30.getText(),ScaleFactor,set.model.ScaleFactor);
    }//GEN-LAST:event_ScaleFactorMouseClicked

    @Override
    public boolean saveSettings() {
        return saveSettings(null);
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ANGLE;
    private javax.swing.JButton ARCGCodeModeButton;
    private javax.swing.JButton AutoCenterButton;
    private javax.swing.JButton AutoScaleButton;
    private javax.swing.JTextField BaudRate;
    private javax.swing.JTextField BlankHight;
    private javax.swing.JTextField BlankWidth;
    private javax.swing.JTextField BlankZ;
    private javax.swing.JButton ContinuousButton;
    private javax.swing.JTextField CutterDiameter;
    private javax.swing.JTextField DeviceName;
    private javax.swing.JTextField DevicePort;
    private javax.swing.JTextField DeviceTimeOut;
    private javax.swing.JTextField FillParametersAngle;
    private javax.swing.JTextField FillParametersAngleInc;
    private javax.swing.JTextField FillParametersFillCell;
    private javax.swing.JTextField FillParametersOffset;
    private javax.swing.JTextField FillParametersRaster;
    private javax.swing.JTextField FillingFlatness;
    private javax.swing.JButton FlateCircuitSliceButton;
    private javax.swing.JButton FullScreenButton;
    private javax.swing.JTextField LineCount;
    private javax.swing.JTextField LineLength;
    private javax.swing.JButton LoopsWithSomeLineTypesButton;
    private javax.swing.JTextField MarkingFieldHight;
    private javax.swing.JTextField MarkingFieldWidth;
    private javax.swing.JComboBox<String> Mode2;
    private javax.swing.JButton MoveOptimizeButton;
    private javax.swing.JTextField MoveProc;
    private javax.swing.JTextField PageServoOffsetsLeft;
    private javax.swing.JTextField PageServoOffsetsTop;
    private javax.swing.JTextField PrintTime;
    private javax.swing.JButton RepairLoopsButton;
    private javax.swing.JButton RotateButton;
    private javax.swing.JTextField SHIFT;
    private javax.swing.JTextField ScaleFactor;
    private javax.swing.JButton SendLoopsButton;
    private javax.swing.JButton ShiftButton;
    private javax.swing.JTextField SliceTime;
    private javax.swing.JTextField StepMinus;
    private javax.swing.JTextField VerticalStep;
    private javax.swing.JTextField WorkFrameX;
    private javax.swing.JTextField WorkFrameY;
    private javax.swing.JTextField WorkFrameZ;
    private javax.swing.JComboBox<String> XYZ;
    private javax.swing.JComboBox<String> XYZShift;
    private javax.swing.JTextField Z;
    private javax.swing.JLabel Z0_10;
    private javax.swing.JLabel Z0_11;
    private javax.swing.JLabel Z0_12;
    private javax.swing.JLabel Z0_13;
    private javax.swing.JLabel Z0_14;
    private javax.swing.JLabel Z0_15;
    private javax.swing.JLabel Z0_16;
    private javax.swing.JLabel Z0_17;
    private javax.swing.JLabel Z0_18;
    private javax.swing.JLabel Z0_19;
    private javax.swing.JLabel Z0_2;
    private javax.swing.JLabel Z0_20;
    private javax.swing.JLabel Z0_21;
    private javax.swing.JLabel Z0_22;
    private javax.swing.JLabel Z0_23;
    private javax.swing.JLabel Z0_24;
    private javax.swing.JLabel Z0_25;
    private javax.swing.JLabel Z0_26;
    private javax.swing.JLabel Z0_27;
    private javax.swing.JLabel Z0_3;
    private javax.swing.JLabel Z0_30;
    private javax.swing.JLabel Z0_4;
    private javax.swing.JLabel Z0_5;
    private javax.swing.JLabel Z0_6;
    private javax.swing.JLabel Z0_7;
    private javax.swing.JLabel Z0_8;
    private javax.swing.JLabel Z0_9;
    private javax.swing.JLabel Z2_1;
    private javax.swing.JLabel Z2_2;
    private javax.swing.JLabel Z2_3;
    private javax.swing.JLabel Z2_4;
    private javax.swing.JLabel Z2_5;
    private javax.swing.JLabel Z2_6;
    private javax.swing.JTextField ZUp;
    private javax.swing.JTextField Zfinish;
    private javax.swing.JTextField Zstart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
