/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package romanow.cnc.view;

import romanow.cnc.Values;
import romanow.cnc.settings.UserProfile;
import romanow.cnc.settings.WorkSpace;
import romanow.cnc.utils.StringCrypter;
import romanow.cnc.utils.UNIException;
import romanow.cnc.view.panels.I_RealValue;
import romanow.cnc.view.panels.KeyBoardPanel;

import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author Admin
 */
public class LoginPanel extends BasePanel {

    /**
     * Creates new form LoginPanel
     */
    private void init(){
        ArrayList<UserProfile> users = WorkSpace.ws().global().userList;
        UserList.removeAll();
        for(UserProfile uu : users){
            UserList.addItem(uu.name);
            }
        // Password.setText("");
        //-------------- Отладка ------------------------
        Password.setText("admin");
        UserList.setSelectedIndex(1);
        }

    private void login(){
        WorkSpace ws = WorkSpace.ws();
        ArrayList<UserProfile> users = ws.global().userList;
        UserProfile user = users.get(UserList.getSelectedIndex());
        if (user.password.equals(StringCrypter.encrypt(Password.getText()))){
            ws.currentUser(user);
            getBaseFrame().setViewPanel(Values.PanelMain | Values.PanelGlobalSettings | Values.PanelCommonView);
            getBaseFrame().refreshPanels();
            }
        else
            MES.setText("Неверный пароль");
        }



    @Override
    public String getName() {
        return "Вход";
        }

    @Override
    public int modeMask() {
        return Values.PanelLogin;
        }

    @Override
    public boolean modeEnabled() {
        return true;
    }

    @Override
    public void onActivate() {
        initView();
        }

    @Override
    public void onDeactivate() {
        }

    @Override
    public void onClose() {
        }

    public LoginPanel(CNCViewer baseFrame) {
        super(baseFrame);
        initComponents();
        setComponentsScale();
        }

    public void initView() {
        WorkSpace ws = WorkSpace.ws();
        try {
            ws.loadGlobalSettings();
            } catch (UNIException e) {
                MES.setText("Настойки не прочитаны - умолчание");
                ws.saveSettings();
            }
        init();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        MES = new javax.swing.JTextField();
        UserList = new javax.swing.JComboBox<>();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Пароль");
        add(jLabel1);
        jLabel1.setBounds(260, 100, 60, 17);

        Password.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordMouseClicked(evt);
            }
        });
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });
        add(Password);
        Password.setBounds(350, 90, 280, 40);

        Login.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Login.setText("Войти");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        add(Login);
        Login.setBounds(490, 150, 140, 40);

        MES.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(MES);
        MES.setBounds(50, 200, 580, 40);

        UserList.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UserList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                UserListItemStateChanged(evt);
            }
        });
        add(UserList);
        UserList.setBounds(350, 40, 280, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        if(evt.getKeyCode()==10){//Enter key
            login();
        }
    }//GEN-LAST:event_PasswordKeyPressed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        login();
    }//GEN-LAST:event_LoginActionPerformed

    private void UserListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_UserListItemStateChanged
    }//GEN-LAST:event_UserListItemStateChanged

    private void PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseClicked
        KeyBoardPanel keyBoard = new KeyBoardPanel("Пароль", Password, true,new I_RealValue() {
            @Override
            public void onEvent(String value) {
                Password.setText(value);
                login();
                }
            });
    }//GEN-LAST:event_PasswordMouseClicked

    @Override
    public void refresh() {
    }

    @Override
    public void onEvent(int code, int par1, long par2, String par3, Object oo) {
    }

    @Override
    public void shutDown() {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JTextField MES;
    private javax.swing.JPasswordField Password;
    private javax.swing.JComboBox<String> UserList;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
