/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package epos.slm3d.m3d;

import lombok.Getter;

/**
 *
 * @author Admin
 */
public abstract class BasePanel extends javax.swing.JPanel implements I_PanelEvent{
    public final static int ModeSettings=0x01;
    public final static int ModeMain=0x02;
    public final static int ModeMilling=0x04;
    public final static int ModePreview=0x08;
    @Getter private BaseFrame baseFrame;
    public abstract  int modeMask();
    public boolean isSelectedMode(int mode){
        return (modeMask() & mode)!=0;
        }
    /**
     * Creates new form BasePanel
     */
    public BasePanel(BaseFrame baseFrame0) {
        initComponents();
        baseFrame = baseFrame0;
        }
    public abstract void sendEvent(int code, int par1, long par2, String par3,Object o);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
