/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package epos.slm3d.m3d;

import epos.slm3d.settings.Settings;
import epos.slm3d.settings.WorkSpace;
import epos.slm3d.settingsView.SliceSettingsPanel;
import epos.slm3d.utils.I_Notify;

/**
 *
 * @author romanow
 */
public class M3DReSlice extends javax.swing.JFrame implements I_SettingsChanged{
    private I_Notify notify;
    private SliceSettingsPanel panel;
    private I_SettingsSelect back;
    /**
     * Creates new form M3DReSlice
     */
    public M3DReSlice(String title,Settings set, boolean edit,I_SettingsSelect back0, I_Notify notify0) {
        initComponents();
        setTitle(title);
        notify = notify0;
        back = back0;
        setBounds(150,150,250,100);
        panel = new SliceSettingsPanel(this,set,notify);
        panel.setBounds(0,70,500,400);
        add(panel);
        panel.setVisible(OwnSettings.isSelected());
        Do.setText(edit ? "Повторный слайсинг" : "Новый слой");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OwnSettings = new javax.swing.JCheckBox();
        Do = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        OwnSettings.setText("Собственные параметры слайсинга");
        OwnSettings.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OwnSettingsItemStateChanged(evt);
            }
        });
        getContentPane().add(OwnSettings);
        OwnSettings.setBounds(10, 10, 220, 23);

        Do.setText("Выполнить");
        Do.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoActionPerformed(evt);
            }
        });
        getContentPane().add(Do);
        Do.setBounds(10, 35, 220, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OwnSettingsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OwnSettingsItemStateChanged
        panel.setVisible(OwnSettings.isSelected());
        if (OwnSettings.isSelected())
            setBounds(150,150,500,400);
        else
            setBounds(150,150,250,100);
    }//GEN-LAST:event_OwnSettingsItemStateChanged

    private void DoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoActionPerformed
        if (OwnSettings.isSelected())
            back.onSelect(panel.copySettings());
        else
            back.onSelect(null);
        dispose();
    }//GEN-LAST:event_DoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Do;
    private javax.swing.JCheckBox OwnSettings;

    @Override
    public void onChange() {

    }

    @Override
    public void onCancel() {

    }
    // End of variables declaration//GEN-END:variables
}
